// londonPoi.ts
import type { Poi } from "./romePoi";

export const londonPoi: Poi[] = [
  {
    id: "westminster-abbey",
    name: "Westminster Abbey",
    category: "church",
    neighborhood: "Westminster",
    themes: ["history", "royal", "architecture"],
  },
  {
    id: "big-ben-parliament",
    name: "Big Ben & Houses of Parliament",
    category: "viewpoint",
    neighborhood: "Westminster",
    themes: ["icons", "history", "river"],
  },
  {
    id: "buckingham-palace",
    name: "Buckingham Palace",
    category: "square",
    neighborhood: "Westminster",
    themes: ["royal", "ceremony", "icons"],
  },
  {
    id: "st-jamess-park",
    name: "St James's Park",
    category: "park",
    neighborhood: "Westminster",
    themes: ["nature", "relax", "royal"],
  },
  {
    id: "trafalgar-square",
    name: "Trafalgar Square",
    category: "square",
    neighborhood: "West End",
    themes: ["icons", "meeting-point", "art"],
  },
  {
    id: "national-gallery",
    name: "The National Gallery",
    category: "museum",
    neighborhood: "West End",
    themes: ["art", "classic", "indoors"],
  },
  {
    id: "covent-garden",
    name: "Covent Garden",
    category: "district",
    neighborhood: "West End",
    themes: ["shopping", "food", "street-performers"],
  },
  {
    id: "british-museum",
    name: "The British Museum",
    category: "museum",
    neighborhood: "Bloomsbury",
    themes: ["history", "world-cultures", "indoors"],
  },
  {
    id: "soho-carnaby",
    name: "Soho & Carnaby Street",
    category: "district",
    neighborhood: "Soho",
    themes: ["nightlife", "shopping", "food"],
  },
  {
    id: "st-pauls-cathedral",
    name: "St Paul's Cathedral",
    category: "church",
    neighborhood: "City of London",
    themes: ["architecture", "views", "history"],
  },
  {
    id: "millennium-bridge-southbank",
    name: "Millennium Bridge & Southbank Walk",
    category: "viewpoint",
    neighborhood: "South Bank",
    themes: ["river-walk", "views", "photography"],
  },
  {
    id: "tate-modern",
    name: "Tate Modern",
    category: "museum",
    neighborhood: "South Bank",
    themes: ["modern-art", "architecture", "indoors"],
  },
  {
    id: "borough-market",
    name: "Borough Market",
    category: "district",
    neighborhood: "Southwark",
    themes: ["food", "market", "local-experience"],
  },
  {
    id: "tower-of-london",
    name: "Tower of London",
    category: "museum",
    neighborhood: "City of London",
    themes: ["history", "royal", "architecture"],
  },
  {
    id: "tower-bridge-riverside",
    name: "Tower Bridge & Riverside Walk",
    category: "viewpoint",
    neighborhood: "City of London",
    themes: ["icons", "views", "river-walk"],
  },
  {
    id: "sky-garden",
    name: "Sky Garden",
    category: "viewpoint",
    neighborhood: "City of London",
    themes: ["views", "modern-architecture", "skyline"],
  },
  {
    id: "camden-market",
    name: "Camden Market & Regent's Canal",
    category: "district",
    neighborhood: "Camden",
    themes: ["alternative", "market", "street-food"],
  },
  {
    id: "regents-park-primrose",
    name: "Regent's Park & Primrose Hill",
    category: "park",
    neighborhood: "Regent's Park",
    themes: ["nature", "views", "relax"],
  },
  {
    id: "hyde-park-kensington",
    name: "Hyde Park & Kensington Gardens",
    category: "park",
    neighborhood: "Kensington",
    themes: ["nature", "relax", "royal"],
  },
  {
    id: "notting-hill-portobello",
    name: "Notting Hill & Portobello Road",
    category: "district",
    neighborhood: "Notting Hill",
    themes: ["colorful", "market", "photography"],
  },
  {
    id: "greenwich-observatory",
    name: "Greenwich Park & Royal Observatory",
    category: "park",
    neighborhood: "Greenwich",
    themes: ["views", "history", "green-space"],
  },

    {
    id: "piccadilly-circus",
    name: "Piccadilly Circus",
    category: "square",
    neighborhood: "West End",
    themes: ["icons", "nightlife", "shopping", "lights"],
  },
  {
    id: "leicester-square",
    name: "Leicester Square",
    category: "square",
    neighborhood: "West End",
    themes: ["cinema", "nightlife", "restaurants"],
  },
  {
    id: "oxford-street",
    name: "Oxford Street",
    category: "street",
    neighborhood: "West End",
    themes: ["shopping", "crowds", "icons"],
  },
  {
    id: "south-kensington-museums",
    name: "South Kensington Museums (V&A, Natural History, Science Museum)",
    category: "district",
    neighborhood: "South Kensington",
    themes: ["museums", "family-friendly", "indoors"],
  },
  {
  id: "shoreditch",
  name: "Shoreditch & Brick Lane",
  category: "district",
  neighborhood: "East London",
  themes: ["street-art", "alternative", "food", "trendy"],
},
{
  id: "south-bank-night",
  name: "Southbank Evening Walk",
  category: "viewpoint",
  neighborhood: "South Bank",
  themes: ["night-view", "photography", "romantic"],
},
{
  id: "kew-gardens",
  name: "Kew Gardens",
  category: "park",
  neighborhood: "Richmond",
  themes: ["botanical", "relax", "nature"],
},

];
